export const CREATE_VOLUNTEER_REQUEST = "CREATE_VOLUNTEER_REQUEST"
export const CREATE_VOLUNTEER_SUCCESS = "CREATE_VOLUNTEER_SUCCESS"
export const CREATE_VOLUNTEER_FAIL = "CREATE_VOLUNTEER_SUCCESS"
export const RESET_VOLUNTEER = 'RESET_VOLUNTEER';
