export const NEWS_FETCH_REQUEST = "NEWS_FETCH_REQUEST";
export const NEWS_FETCH_SUCCESS = "NEWS_FETCH_SUCCESS";
export const NEWS_FETCH_FAIL = "NEWS_FETCH_FAIL";

export const NEWS_CREATE_REQUEST = "NEWS_CREATE_REQUEST";
export const NEWS_CREATE_SUCCESS = "NEWS_CREATE_SUCCESS";
export const NEWS_CREATE_FAIL = "NEWS_CREATE_FAIL";

export const NEWS_CREATE_RESET = "NEWS_CREATE_RESET"